# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git’
platform :ios, '9.0'


target 'SmartUtils_Example' do
  pod 'SmartUtils', :path => '../'

  target 'SmartUtils_Tests' do
    inherit! :search_paths

    
  end
end
